version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=local
      - CONNECTION_STRING=mongodb://mongo:27017/Netflix_database
      - PORT=8080
      - DOCKER_ENV=true
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cpp_server:
    build:
      context: ./cpp_server
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./data:/data
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  mongo-data:
